import {mkdir, mkdtemp, readFile, rm, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const temporaryDirectory = await mkdtemp(join(tmpdir(), 'rrule-temporal-wasm-'));
const wasmPath = join(temporaryDirectory, 'recurrence.wasm');
const ascPath = resolve(projectRoot, 'node_modules/assemblyscript/bin/asc.js');

try {
  const result = spawnSync(
    process.execPath,
    [ascPath, '--config', resolve(projectRoot, 'asconfig.json'), '--target', 'release', '--outFile', wasmPath],
    {cwd: projectRoot, encoding: 'utf8'},
  );

  if (result.status !== 0) {
    process.stderr.write(result.stdout ?? '');
    process.stderr.write(result.stderr ?? '');
    throw result.error ?? new Error(`AssemblyScript compiler exited with status ${result.status ?? 'unknown'}`);
  }

  const bytes = await readFile(wasmPath);
  const rows = [];
  for (let offset = 0; offset < bytes.length; offset += 24) {
    rows.push(`  ${[...bytes.subarray(offset, offset + 24)].join(', ')},`);
  }

  const source =
    `// Generated by scripts/build-wasm.mjs. Do not edit by hand.\n` +
    `// prettier-ignore\n` +
    `export const RECURRENCE_WASM_BYTES = new Uint8Array([\n${rows.join('\n')}\n]);\n`;
  await mkdir(resolve(projectRoot, 'src/generated'), {recursive: true});
  await writeFile(resolve(projectRoot, 'src/generated/recurrence-wasm.ts'), source);
} finally {
  await rm(temporaryDirectory, {recursive: true, force: true});
}
